---
sudo: false
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec SPEC_OPTS='--format documentation'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.6
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2"
    - PUPPET_GEM_VERSION="~> 3.4"
    - PUPPET_GEM_VERSION="~> 3.8"
    - PUPPET_GEM_VERSION="~> 3.8" FUTURE_PARSER="yes"
    - PUPPET_GEM_VERSION="~> 4.2" STRICT_VARIABLES="yes"
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.2"
notification:
  email: false
